#!/etc/s6-overlay/s6-user-bash
set -e

echo "Starting System By S6-Overlay"

#########################################################################
# 处理服务状态

# if [[ "${KASM_SVC_AUDIO}" == "1" ]]; then
#     sudo rm -f /etc/s6-overlay/s6-rc.d/user/contents.d/svc-audio-out
#     sudo rm -f /etc/s6-overlay/s6-rc.d/user/contents.d/svc-audio-out-ws
#     echo "Enabling Audio Output"
# else 
#     sudo touch /etc/s6-overlay/s6-rc.d/user/contents.d/svc-audio-out
#     sudo touch /etc/s6-overlay/s6-rc.d/user/contents.d/svc-audio-out-ws
#     echo "Disabling Audio Output"
# fi

# if [[ "${KASM_SVC_AUDIO_INPUT}" == "1" ]]; then
#     sudo rm -f /etc/s6-overlay/s6-rc.d/user/contents.d/svc-audio-in
#     echo "Enabling Audio Input"
# else 
#     sudo touch /etc/s6-overlay/s6-rc.d/user/contents.d/svc-audio-in
#     echo "Disabling Audio Input"
# fi

# if [[ "${KASM_SVC_UPLOADS}" == "1" ]]; then
#     sudo rm -f /etc/s6-overlay/s6-rc.d/user/contents.d/svc-upload
#     echo "Enabling Uploads"
# else 
#     sudo touch /etc/s6-overlay/s6-rc.d/user/contents.d/svc-upload
#     echo "Disabling Uploads"
# fi

# if [[ "${KASM_SVC_GAMEPAD}" == "1" ]]; then
#     sudo rm -f /etc/s6-overlay/s6-rc.d/user/contents.d/svc-gamepad
#     echo "Enabling Gamepad"
# else 
#     sudo touch /etc/s6-overlay/s6-rc.d/user/contents.d/svc-gamepad
#     echo "Disabling Gamepad"
# fi

# if [[ "${START_XFCE4:-1}" == "1" ]]; then
#     sudo rm -f /etc/s6-overlay/s6-rc.d/user/contents.d/svc-kasmwin
#     echo "Enabling XFCE4"
# else 
#     sudo touch /etc/s6-overlay/s6-rc.d/user/contents.d/svc-kasmwin
#     echo "Disabling XFCE4"
# fi

#########################################################################
# 处理证书配置

# ${HOME}/.vnc/self.pem不存在，新建自签证书
if [[ ! -f ${HOME}/.vnc/self.pem ]]; then
    # Create cert for KasmVNC
    echo "Creating self-signed cert for KasmVNC"
    mkdir -p ${HOME}/.vnc
    openssl req -x509 -nodes -days 3650 -newkey rsa:2048 \
    -keyout ${HOME}/.vnc/self.pem \
    -out    ${HOME}/.vnc/self.pem \
    -subj "/C=CN/ST=LN/L=DL/O=None/OU=SSC/CN=*"
fi

# 检查自签证书是否过期?? 跳过

# tmpval=$VNC_VIEW_ONLY_PW
# unset VNC_VIEW_ONLY_PW
# VNC_VIEW_ONLY_PW=$tmpval
# tmpval=$VNC_PW
# unset VNC_PW
# VNC_PW=$tmpval
# first entry is control, second is view (if only one is valid for both)
mkdir -p "$HOME/.vnc"
PASSWD_PATH="$HOME/.kasmpasswd"
if [[ -f $PASSWD_PATH ]]; then
    echo -e "purging existing VNC password settings"
    rm -f $PASSWD_PATH
fi

VNC_PW_HASH=$(python3 -c "import crypt; print(crypt.crypt('${VNC_PW}', '\$5\$kasm\$'));")
VNC_VIEW_PW_HASH=$(python3 -c "import crypt; print(crypt.crypt('${VNC_VIEW_ONLY_PW}', '\$5\$kasm\$'));")
echo "kasm_user:${VNC_PW_HASH}:ow" > $PASSWD_PATH
echo "kasm_viewer:${VNC_VIEW_PW_HASH}:" >> $PASSWD_PATH
# echo "kams_user:$(openssl passwd -apr1 ${VNC_PW}):ow" > $PASSWD_PATH
# echo "kasm_viewer:$(openssl passwd -apr1 ${VNC_VIEW_PW_HASH}):ow" >> $PASSWD_PATH
chmod 600 $PASSWD_PATH

# 更改文件权限，否则 firefox 无法启动
if [ "$KASM_USER" == "root" ] || [ "$KASM_USER" == "" ] ; then
    chown root $HOME
fi