serverAddr = "{{ .Envs.FRP_ADDR }}"
serverPort = {{ .Envs.FRP_PORT }}
auth.token = "{{ .Envs.FRP_TOKEN }}"
user = "{{ .Envs.FRP_USER }}"

# https， 后端需要支持 proxy_protocol

[[proxies]]
name = "vsc"
type = "https"
localPort = 7001
customDomains = ["{{ .Envs.FRP_DN_VSC }}"]
transport.proxyProtocolVersion = "v2"

[[proxies]]
name = "dsk"
type = "https"
localPort = 7101
customDomains = ["{{ .Envs.FRP_DN_DSK }}"]
transport.proxyProtocolVersion = "v2"
