## x. ccc 安装软件
ARG BASE_IMAGE_TAG

# FROM ghcr.io/suisrc/webtop:${BASE_IMAGE_TAG}
FROM ghcr.io/suisrc/webtop:xfce-vscode-2.1.1
# ================================================================

USER debian
RUN sudo add-msedge && sudo fix-mchina