## x. playwirght
ARG BASE_IMAGE_TAG

FROM ghcr.io/suisrc/webtop:${BASE_IMAGE_TAG}-vsas
# ================================================================

## install playwright-ts and playwright-go
RUN npm install -g typescript playwright &&\
    go get github.com/playwright-community/playwright-go

RUN playwright install firefox --with-deps
