## x. 最后安装 nodejs, java， golang 等开发环境, all in one, BASE_IMAGE_TAG = vscode / xfce
# python 环境， 可以直接命令行安装，这边不作为基础环境
ARG BASE_IMAGE_TAG

FROM ghcr.io/suisrc/webtop:${BASE_IMAGE_TAG}
# ================================================================

RUN mkdir -p ${HOME}/.go/bin
ENV GO_VERSION=1.24.4  \
    GOPATH=${HOME}/.go \
    PATH=/usr/local/golang/bin:${HOME}/.go/bin:$PATH

# ==============================================================================================================
# https://golang.google.cn/dl/
RUN mkdir /usr/local/golang && \
    curl -fSL --compressed "https://dl.google.com/go/go${GO_VERSION}.linux-amd64.tar.gz" | \
    tar -xz -C /usr/local/golang --strip-components=1 &&\
    go version
    # ; exit 0

RUN bash &&\
    sdk install java 8.0.452-sem &&\
    sdk install java 17.0.15-sem &&\
    sdk install maven

RUN bash &&\
    nvm install 24 &&\
    nvm install 14

# ==============================================================================================================
# golang extension
# RUN go install github.com/ramya-rao-a/go-outline@latest &&\
#     go install github.com/cweill/gotests/gotests@latest &&\
#     go install github.com/fatih/gomodifytags@latest &&\
#     go install github.com/josharian/impl@latest &&\
#     go install github.com/haya14busa/goplay/cmd/goplay@latest &&\
#     go install github.com/go-delve/delve/cmd/dlv@latest &&\
#     go install honnef.co/go/tools/cmd/staticcheck@latest &&\
#     go install golang.org/x/tools/gopls@latest &&\
#     go install github.com/google/wire/cmd/wire@latest; exit 0

# python extension
# RUN pip3 install --upgrade pip &&\
#     pip3 install --user pylint &&\
#     pip3 install --user django
