##  browser-use
ARG BASE_IMAGE_TAG

# ${BASE_IMAGE_TAG} 为基础镜像版本
FROM ghcr.io/suisrc/webtop:ccc-2.2.1
# ================================================================
# 部署和运行 browser-use
# https://github.com/browser-use/web-ui


# Install Chrome
RUN add-chrome &&\
    apt-get autoremove && apt-get clean && \
    rm -rf /tmp/* /var/tmp/* /var/lib/apt/lists/*

