FROM golang:1.26-trixie as builder

RUN apt-get update && apt-get install -y git
COPY tools/kss/ /kss/
RUN cd /ssh/ && CGO_ENABLED=0 go build -ldflags="-s -w" -o kss .

FROM debian:trixie-slim
# ================================================================
# KEYS_FOLDER, LISTEN_ADDR, TARGET_ADDR
USER root

RUN apt-get update && apt-get install -y \
    ca-certificates curl openssh-client &&\
    apt-get autoremove && apt-get clean && \
    rm -rf /tmp/* /var/tmp/* /var/lib/apt/lists/*

COPY --from=builder /kss/kss /kss/kssh /usr/bin/

WORKDIR /root
CMD ["/usr/bin/kssh"]
