FROM golang:1.26-trixie as builder

RUN apt-get update && apt-get install -y git
COPY tools/kvs/ /kvs/
RUN cd /kvs/ && CGO_ENABLED=0 go build -ldflags="-s -w" -o kvs .
COPY tools/kas/ /kas/
RUN cd /kas/ && CGO_ENABLED=0 go build -ldflags="-s -w" -o kas .
RUN mkdir /app/ && mv /kvs/kvs /kas/kas /app/

FROM debian:trixie-slim

RUN apt-get update && apt-get install -y \
    ca-certificates curl openssh-client openssh-server &&\
    apt-get autoremove && apt-get clean && \
    rm -rf /tmp/* /var/tmp/* /var/lib/apt/lists/*

# set environment variables
ENV KAS_SSHD="0" \
    KAS_VSCODE="1" \
    VSCODE_WSC="/wsc" \
    VSCODE_PORT="7080" \
    PASSWORD="" \
    PASSROOT=""

COPY --from=builder  /app/  /usr/bin/

COPY rootfs/ /
COPY srv/init.sh srv/vscode.sh /usr/srv
COPY script/vscode.kas.ini /etc/kas.ini

ENTRYPOINT ["/usr/bin/kas", "-c"]

# EXPOSE 7080