ARG BASE_IMAGE_TAG

FROM golang:1.26-trixie as builder

RUN apt-get update && apt-get install -y git
COPY tools/kvs/ /kvs/
RUN cd /kvs/ && CGO_ENABLED=0 go build -ldflags="-s -w" -o kvs .
COPY tools/kas/ /kas/
RUN cd /kas/ && CGO_ENABLED=0 go build -ldflags="-s -w" -o kas .
RUN mkdir /app/ && mv /kvs/kvs /kas/kas /app/


# FROM ghcr.io/suisrc/webtop:${BASE_IMAGE_TAG}
FROM ghcr.io/suisrc/webtop:xfce-3.5.5
# ================================================================

ENV DEBIAN_FRONTEND=noninteractive \
    DISPLAY=:1 \
    TITLE="webtop" \
    KAS_WEBTOP="1" \
    KAS_SSHD="0" \
    KAS_VSCODE="0" \
    PASSWORD="" \
    PASSROOT="" \
    GIT_USER_NAME="" \
    GIT_USER_EMAIL="" \
    GOROOT="/usr/local/golang" \
    GOPATH="/root/.go" \
    PATH="/usr/local/golang/bin:/root/.go/bin:${PATH}" \
    USER="root"

COPY --from=builder  /app/  /usr/bin/

COPY rootfs/ /
COPY srv/*   /usr/srv/
COPY script/webtop.kas.ini /etc/kas.ini

ENTRYPOINT ["/usr/bin/kas", "-c"]

# EXPOSE 7090
