FROM golang:1.26-trixie as builder

RUN apt-get update && apt-get install -y git
COPY tools/kvs/ /kvs/
RUN cd /kvs/ && CGO_ENABLED=0 go build -ldflags="-s -w" -o kvs .
COPY tools/kas/ /kas/
RUN cd /kas/ && CGO_ENABLED=0 go build -ldflags="-s -w" -o kas .
RUN mkdir /app/ && mv /kvs/kvs /kas/kas /app/


# ARG BASE_IMAGE_TAG
# FROM ghcr.io/suisrc/webtop:base-${BASE_IMAGE_TAG}
FROM ghcr.io/suisrc/webtop:base-3.5.3

# set environment variables
ENV KAS_SSHD="0" \
    KAS_VSCODE="1" \
    VSCODE_WSC="/wsc" \
    VSCODE_PORT="7080" \
    PASSWORD="" \
    PASSROOT="" \
    GIT_USER_NAME="" \
    GIT_USER_EMAIL="" \
    GOROOT="/usr/local/golang" \
    GOPATH="/root/.go" \
    PATH="/usr/local/golang/bin:/root/.go/bin:${PATH}" \
    USER="root"

COPY --from=builder  /app/  /usr/bin/

COPY rootfs/ /
COPY srv/init.sh srv/vscode.sh /usr/srv/
COPY script/vscode.kas.ini /etc/kas.ini

ENTRYPOINT ["/usr/bin/kas", "-c"]

# EXPOSE 7080