ARG BASE_IMAGE_TAG
FROM ghcr.io/suisrc/webtop:${BASE_IMAGE_TAG}


RUN apt update && DEBIAN_FRONTEND=noninteractive \
    apt install --no-install-recommends -y \
    fonts-powerline && \
    fc-cache -f -v && \
    apt-get autoremove && apt-get clean && \
    rm -rf /tmp/* /var/tmp/* /var/lib/apt/lists/*

COPY rootfs/ /
RUN sed -i "1iexport \$(sudo cat /proc/1/environ |tr '\\\\0' '\\\\n' | xargs)\n" ${HOME}/.bashrc && \
    sed -i "1iexport \$(sudo cat /proc/1/environ |tr '\\\\0' '\\\\n' | xargs)\n" ${HOME}/.zshrc && \
    sed -i 's/^# C.UTF-8/C.UTF-8/' /etc/locale.gen

ENV LANGUAGE="zh_CN:zh" \
    LANG="zh_CN.UTF-8" \
    LC_ALL="zh_CN.UTF-8" \
    LC_CTYPE="zh_CN.UTF-8"