#!/usr/bin/with-contenv zsh


## GIT_USER_NAME = 
## GIT_USER_EMAIL = 
## VSX_MICROSOFT = false
## VSX_SERVICE_URL = https://open-vsx.org/vscode/gallery
## VSX_ITME_URL = https://open-vsx.org/vscode/item
## VSX_RESOURCE_URL = https://open-vsx.org/vscode/asset/{publisher}/{name}/{version}/Microsoft.VisualStudio.Code.WebResources/{path}
## EXTENSIONS = 

echo 'init vscode server ...'
if [ $GIT_USER_NAME ]; then
    git config --global user.name "$GIT_USER_NAME"
    #git config pull.rebase false
    if [ $GIT_USER_EMAIL ]; then
        git config --global user.email "$GIT_USER_EMAIL"
    fi
fi
if [ $VSX_MICROSOFT ]; then
    grep -rl open-vsx.org /vsc/**/*.js /vsc/**/*.json /vsc/**/*.map | xargs sed -i \
    -e 's|open-vsx.org/vscode/gallery|marketplace.visualstudio.com/_apis/public/gallery|g' \
    -e 's|open-vsx.org/vscode/item|marketplace.visualstudio.com/items|g' \
    -e 's|open-vsx.org/vscode/asset/{publisher}/{name}/{version}/Microsoft.VisualStudio.Code.WebResources/{path}|{publisher}.vscode-unpkg.net/{publisher}/{name}/{version}/{path}|g'
else
    if [ $VSX_SERVICE_URL ]; then
        grep -rl open-vsx.org /vsc/**/*.js | xargs sed -i "s|https://open-vsx.org/vscode/gallery|$VSX_SERVICE_URL|g"
    fi
    if [ $VSX_ITME_URL ]; then
        grep -rl open-vsx.org /vsc/**/*.js | xargs sed -i "s|https://open-vsx.org/vscode/item|$VSX_ITME_URL|g"
    fi
    if [ $VSX_RESOURCE_URL ]; then
        grep -rl open-vsx.org /vsc/**/*.js | xargs sed -i "s|https://open-vsx.org/vscode/asset/{publisher}/{name}/{version}/Microsoft.VisualStudio.Code.WebResources/{path}|$VSX_RESOURCE_URL|g"
    fi
fi
echo 'install vscode extension ...'
# bash read -ra, zsh read -rA
if [ $EXTENSIONS ]; then
    IFS=','
    read -rA exts <<<"$EXTENSIONS"
    for i in "${exts[@]}"; do
        code-server --install-extension $i
    done
fi

# 更改文件权限，否则 firefox 无法启动
if [[ "$USERNAME" == "root" ]] || [[ "$USERNAME" == "" ]] ; then
    # chown -R root:root $HOME
    echo "init vscode server by root"
else
    echo "init vscode server by user"
    sudo chown -R $USERNAME:$USERNAME $HOME
fi

echo 'init vscode server end'