#!/usr/bin/with-contenv bash


if [[ "${SVC_VSCODE}" == "0" ]]; then
    echo 'disable sshd server ...'
    s6-svc -O exit
fi

echo 'start sshd server ...'
## VSC_ARGS: vscode参数
code-server --host ${VSC_HOST:-0.0.0.0} --port ${VSC_PORT:-7000} $VSC_ARGS /wsc
