#!/usr/bin/with-contenv bash

if [[ "${SVC_KCLIENT}" == "0" ]]; then
    echo 'disable kclient server ...'
    sleep 1
    sudo s6-rc stop svc-kclient
    exit
fi

# NodeJS wrapper
cd /kclient
exec node index.js
