#!/bin/sh

# 处理默认bus， edge需要，其他应用不清楚
sudo rm -f /run/dbus/system_bus_socket && sudo mkdir -p /run/dbus/
# create a new session bus, --nofork
system_bus_pid=$(sudo /usr/bin/dbus-daemon --system --print-pid --nopidfile --address=unix:path=/run/dbus/system_bus_socket)
# 更改权限，否则其他用户无法连接dbus, 这个必须的，所以不能使用--nofork参数
sudo chmod a+r /run/dbus/system_bus_socket

# system_bus_pid=$(cat /run/dbus/pid)
wait $system_bus_pid