#!/usr/bin/with-contenv bash

# 更改文件权限，否则 firefox 无法启动
if [[ "$USER" == "root" ]] || [[ "$USER" == "" ]] ; then
    # chown -R root:root $HOME
    echo "init services server by root"
else
    echo "init services server by user"
    sudo chown -R $USER:$USER $HOME
fi
