#!/usr/bin/with-contenv bash

# 更改文件权限，否则 firefox 无法启动
if [[ "$USER" == "root" ]] || [[ "$USER" == "" ]] ; then
    # chown -R root:root $HOME
    echo "init services server by root"
else
    echo "init services server by $USER"
    sudo chown -R $USER:$USER $HOME
fi

if [[ ! -f "/tmp/.X11-unix" ]]; then
  mkdir /tmp/.X11-unix /tmp/.X11-pipe 2>/dev/null
  chmod 1777 /tmp/.X11-unix /tmp/.X11-pipe
fi
# =============================================================================================

# echo "**** printer config ****"
# sed -i -r -e "s:^(Out\s).*:\1/home/$USER/PDF:" /etc/cups/cups-pdf.conf

# echo "**** filesystem setup ****"
# ln -s /usr/local/share/kasmvnc /usr/share/kasmvnc
# ln -s /usr/local/etc/kasmvnc /etc/kasmvnc
# ln -s /usr/local/lib/kasmvnc /usr/lib/kasmvncserver

# echo "**** openbox tweaks ****" 
# sed -i \
#   -e 's/NLIMC/NLMC/g' \
#   -e '/debian-menu/d' \
#   -e 's|</applications>|  <application class="*"><maximized>yes</maximized></application>\n</applications>|' \
#   -e 's|</keyboard>|  <keybind key="C-S-d"><action name="ToggleDecorations"/></keybind>\n</keyboard>|' \
#   /etc/xdg/openbox/rc.xml

# echo "**** proot-apps ****"
# mkdir /proot-apps/
# PAPPS_RELEASE=$(curl -sX GET "https://api.github.com/repos/linuxserver/proot-apps/releases/latest" \
#   | awk '/tag_name/{print $4;exit}' FS='[""]') 
# curl -L https://github.com/linuxserver/proot-apps/releases/download/${PAPPS_RELEASE}/proot-apps-x86_64.tar.gz \
#   | tar -xzf - -C /proot-apps/
# echo "${PAPPS_RELEASE}" > /proot-apps/pversion

# echo "**** kasm support ****"
# KASMBINS_RELEASE="1.15.0"

# mkdir -p /var/run/pulse
# chown 1000:root /var/run/pulse
# mkdir -p /kasmbins
# curl -s https://kasm-ci.s3.amazonaws.com/kasmbins-amd64-${KASMBINS_RELEASE}.tar.gz | tar xzvf - -C /kasmbins/ 
# chmod +x /kasmbins/*
# chown -R 1000:1000 /kasmbins

# echo "**** locales ****"
# for LOCALE in $(curl -sL https://raw.githubusercontent.com/thelamer/lang-stash/master/langs); do
#   localedef -i $LOCALE -f UTF-8 $LOCALE.UTF-8;
# done

# echo "**** themes ****"
# curl -s https://raw.githubusercontent.com/thelamer/lang-stash/master/theme.tar.gz
#   | tar xzvf - -C /usr/share/themes/Clearlooks/openbox-3/