#!/command/with-contenv bash
set -e

echo 'Starting gamepad server'
exec s6-setuidgid kasm-user $STARTUPDIR/gamepad/kasm_gamepad_server --ssl --auth-token "kasm_user:$VNC_PW" --cert ${HOME}/.vnc/self.pem --certkey ${HOME}/.vnc/self.pem

