#!/command/with-contenv bash
set -e

echo 'Starting audio input server'
exec s6-setuidgid 1000 $STARTUPDIR/audio_input/kasm_audio_input_server --ssl --auth-token "kasm_user:$VNC_PW" --cert ${HOME}/.vnc/self.pem --certkey ${HOME}/.vnc/self.pem
