#!/usr/bin/with-contenv bash
set -e
echo "init kasm config ..."

# default file copies first run
if [[ ! -f "${HOME}/.config/openbox/autostart" ]]; then
  mkdir -p  ${HOME}/.config/openbox
  cp /defaults/autostart ${HOME}/.config/openbox/autostart
fi
if [[ ! -f "${HOME}/.config/openbox/menu.xml" ]]; then
  mkdir -p  ${HOME}/.config/openbox
  cp /defaults/menu.xml ${HOME}/.config/openbox/menu.xml
fi
if [[ -f /usr/local/etc/kasmvnc/kasmvnc.yaml.lsio ]]; then
  sudo mv /usr/local/etc/kasmvnc/kasmvnc.yaml.lsio /usr/local/etc/kasmvnc/kasmvnc.yaml
fi
# XDG Home
sudo printf "${HOME}/.XDG" > /run/s6/container_environment/XDG_RUNTIME_DIR
if [ ! -d "${HOME}/.XDG" ]; then
  mkdir -p ${HOME}/.XDG
fi

# config -> home/user
sudo sed -i "s|/config|${HOME}|" /kclient/index.js
