#!/command/with-contenv bash
set -e

echo 'Starting audio websocket server'
exec s6-setuidgid 1000 $STARTUPDIR/jsmpeg/kasm_audio_out-linux kasmaudio 8081 4901 ${HOME}/.vnc/self.pem ${HOME}/.vnc/self.pem "kasm_user:$VNC_PW"
