#!/command/with-contenv bash

# nginx Path
NGINX_CONFIG=/etc/nginx/conf.d/default.conf

# user passed env vars
CH1PORT="${NOVNC_PORT:-7000}"
CH2PORT="${NOVNC_PORT:-7001}"
VNCUSER="${NOVNC_USER:-wsc}"

# create self signed cert
if [ ! -f "/home/wsc/.vnc/cert.pem" ]; then
  mkdir -p /home/wsc/.vnc/
  openssl req -new -x509 \
    -days 3650 -nodes \
    -out    /home/wsc/.vnc/cert.pem \
    -keyout /home/wsc/.vnc/cert.key \
    -subj "/C=CN/ST=LN/L=DL/O=suisrc/OU=SSC/CN=*"
  chmod 600 /home/wsc/.vnc/cert.key
  chown -R 1000:1000 /home/wsc/.vnc
fi

# modify nginx config
cp -f /defaults/nginx.conf ${NGINX_CONFIG}
sed -i "s/7000/$CH1PORT/g" ${NGINX_CONFIG}
sed -i "s/7001/$CH2PORT/g" ${NGINX_CONFIG}
if [ ! -z ${DISABLE_IPV6+x} ]; then
  sed -i '/listen \[::\]/d' ${NGINX_CONFIG}
fi
if [ ! -z ${NOVNC_PASS+x} ]; then
  printf "${VNCUSER}:$(openssl passwd -apr1 ${NOVNC_PASS})\n" > /etc/nginx/.htpasswd
  sed -i 's/##//g' ${NGINX_CONFIG}
fi
