serverAddr = "{{ .Envs.FRP_ADDR }}"
serverPort = {{ .Envs.FRP_PORT }}
auth.token = "{{ .Envs.FRP_TOKEN }}"
user = "{{ .Envs.FRP_USER }}"

# http, 使用 FRP_USER 作为子域名， 注意，当前会丢失应用授权信息
# 因为是 http，所以传输过程中最好进行加密， useEncryption = true

[[proxies]]
name = "vsc"
type = "http"
localPort = 6801
customDomains = ["{{ .Envs.FRP_DS_VSC }}"]
transport.useEncryption = true
transport.useCompression = false

[[proxies]]
name = "dsk"
type = "http"
localPort = 6900
locations = ["/"]
customDomains = ["{{ .Envs.FRP_DS_DSK }}"]
transport.useEncryption = true
transport.useCompression = false

[[proxies]]
name = "vnc"
type = "http"
localPort = 6901
locations = ["/websockify"]
customDomains = ["{{ .Envs.FRP_DS_DSK }}"]
transport.useEncryption = true
transport.useCompression = false
