serverAddr = "{{ .Envs.FRP_ADDR }}"
serverPort = {{ .Envs.FRP_PORT }}
auth.token = "{{ .Envs.FRP_TOKEN }}"
user = "{{ .Envs.FRP_USER }}"

[[proxies]]
name = "vsc"
type = "http"
localPort = 6801
subdomain = "vsc-{{ .Envs.FRP_USER }}"
httpUser = "{{ .Envs.USER }}"
httpPassword = "{{ .Envs.PASSWORD }}"
transport.useEncryption = true
transport.useCompression = false

[[proxies]]
name = "dsk"
type = "http"
localPort = 6900
locations = ["/"]
subdomain = "dsk-{{ .Envs.FRP_USER }}"
httpUser = "{{ .Envs.USER }}"
httpPassword = "{{ .Envs.PASSWORD }}"
transport.useEncryption = true
transport.useCompression = false

[[proxies]]
name = "vnc"
type = "http"
localPort = 6901
locations = ["/websockify"]
subdomain = "dsk-{{ .Envs.FRP_USER }}"
httpUser = "{{ .Envs.USER }}"
httpPassword = "{{ .Envs.PASSWORD }}"
transport.useEncryption = true
transport.useCompression = false
