# docker-compose -f centos.test.yaml build
version: "3.7"
services:
  code-server:
    build:
      context: ./
      dockerfile: centos.Dockerfile
      args:
        LINUX_MIRRORS: https://mirrors.aliyun.com
        FONT_URL: http://172.17.0.1:9010/github/fonts/sarasa-gothic-ttf-0.10.2-sc.7z
        CODE_URL: http://172.17.0.1:9010/github/code-server2.1698-vsc1.41.1-linux-x86_64.tar.gz
        OH_MY_ZSH_SH_URL: https://gitee.com/ncr/ohmyzsh/raw/sc/tools/install.sh
        OH_MY_ZSH_SUGGES: https://gitee.com/ncr/zsh-autosuggestions
    image: suisrc/code-server:v1.41.1-centos7
    environment:
    - GIT_USER_NAME=suisrc
    - GIT_USER_EMAIL=z@suisrc.cn
    - TZ=Asia/Shanghai
    - PASSWORD=123456
    #volumes:
    #- /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 7770:7000
    restart: unless-stopped
