#!/command/with-contenv bash
if [[ $EXTENSIONS ]]; then
    IFS=','
    read -ra exts <<<"$EXTENSIONS"
    for i in "${exts[@]}"; do
        code --install-extension $i
    done
fi

# init extensions / ?execlineb, 推荐一下插件
# code --install-extension mhutchie.git-graph      #git
# code --install-extension esbenp.prettier-vscode  #edit
# code --install-extension humao.rest-client       #rest
# code --install-extension GitHub.copilot          #dev
