
[program:init]
command=/usr/srv/init.sh
type=once
priority=1
autostart=true
autorestart=false

[program:sshd]
command=/usr/sbin/sshd -D
type=long
priority=10
autostart=${KAS_SSHD}
autorestart=true
depends=init

[program:vscode]
command=/usr/srv/vscode.sh
type=long
priority=11
autostart=${KAS_VSCODE}
autorestart=true
; user=${USER}
