#!/command/with-contenv bash
set -e

echo 'Starting kasmwin server'

if [ -f /opt/VirtualGL/bin/vglrun ] && [ ! -z "${KASM_EGL_CARD}" ] && [ ! -z "${KASM_RENDERD}" ] && [ -O "${KASM_RENDERD}" ] && [ -O "${KASM_EGL_CARD}" ] ; then
	echo "Starting XFCE with VirtualGL using EGL device ${KASM_EGL_CARD}"
	DISPLAY=:1 /opt/VirtualGL/bin/vglrun -d "${KASM_EGL_CARD}" /usr/bin/startxfce4 --replace &
else
	echo "Starting XFCE without VirtualGL"
	if [ -f '/usr/bin/zypper' ]; then
		DISPLAY=:1 /usr/bin/dbus-launch /usr/bin/startxfce4 --replace &
	else
		/usr/bin/startxfce4 --replace &
	fi
fi

kasmvnc_pid=$!

wait $kasmvnc_pid
