#!/usr/bin/with-contenv bash

if [[ "${SVC_SSHD}" == "0" ]]; then
    echo 'disable sshd server ...'
    sleep 1
    sudo s6-rc stop svc-sshd
    exit
fi

if [ ! -f '/etc/ssh/_init' ]; then
    echo `date` > /etc/ssh/_init
    echo 'init sshd for keys ...'
    mkdir /run/sshd
    # sshd-keygen,初始化
    echo y | ssh-keygen -q -t rsa -N '' -f /etc/ssh/ssh_host_rsa_key
    echo y | ssh-keygen -q -t rsa -N '' -f /etc/ssh/ssh_host_dsa_key
    echo y | ssh-keygen -q -t rsa -N '' -f /etc/ssh/ssh_host_ecdsa_key
    echo y | ssh-keygen -q -t rsa -N '' -f /etc/ssh/ssh_host_ed25519_key
    # 配置root的登录密码
    echo ''
    if [[ -n "${USER}" ]] && [[ "$USER" != "root" ]] ; then
        echo "init sshd for ${USER} ..."
        echo "${USER}:${PASSWORD}" | chpasswd
    fi
    echo "PasswordAuthentication yes" >> /etc/ssh/sshd_config
    # 配置root用户的ssh password
    if [[ -n "${PASSROOT}" ]]; then
        echo 'init sshd for root ...'
        echo "root:${PASSROOT}" | chpasswd
        echo "PermitRootLogin yes" >> /etc/ssh/sshd_config
    fi
fi

echo 'start sshd server ... '
exec /usr/sbin/sshd -D
