# docker-compose -f test.yaml build
# git config --global user.name "suisrc"
# git config --global user.email "z@suisrc.cn"
# git clone -b  <分支> <版本库的网址> <本地目录名>
# GIT_REPO_URLS <版本库的网址>|<分支>|<本地目录名>
# rm -rf .git && git init # 清除git并且重新初始化git
version: "3.7"
services:
  nodejs-dev:
    build:
      context: ./
      dockerfile: Dockerfile
    image: suisrc/vscode:v0.0.007
    container_name: nodejs-dev
    environment:
    - GIT_USER_NAME=suisrc
    - GIT_USER_EMAIL=z@suisrc.cn
    #- GIT_REPO_URLS=https://gitee.com/ncr/github.git||master;https://gitee.com/ncr/github.git|sc|sc
    - GIT_REPO_URLS=https://gitee.com/ncr/github.git||.
    - TZ=Asia/Shanghai
    - PASSWORD=123456
    volumes:
    - E:\docker\project\kratos\source:/home/project
    - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 7777:7777
      - 7001:7001
    restart: unless-stopped