#!/command/with-contenv bash
# shellcheck shell=bash

nginx -g "daemon off;" &
inotifywait -e modify,move,create,delete -mr --timefmt '%d/%m/%y %H:%M' --format '%T' /etc/nginx/conf.d/ | while read date time; do
    echo "At ${time} on ${date}, config file update detected."
    nginx -s reload
done

## /usr/local/openresty/nginx/sbin/nginx