#!/usr/bin/with-contenv bash

if [[ "${SVC_NGINX}" == "0" ]]; then
    echo 'disable nginx server ...'
    sleep 1
    sudo s6-rc stop svc-nginx
    exit
fi

# echo 'starting nginx server'
# /usr/local/openresty/nginx/sbin/nginx -> /usr/local/bin/nginx
if [ ! `pgrep nginx` ]; then
    echo "nginx is not running, start it..."
    nginx -g "daemon off;" &
else
    echo "nginx is running, no need to start"
fi

# 监控nginx配置文件变化，自动reload
last_time=
inotifywait -e modify,move,create,delete -mr --timefmt '%d/%m/%y %H:%M' --format '%T' /etc/nginx/conf.d/ | while read date time; do
    # 如果最后修改的时间和当前时间相同，不执行
    if [[ "$last_time" == "$time" ]]; then
        continue
    fi
    last_time=$time
    # 执行更改处理
    echo "At ${time} on ${date}, config file update detected."
    nginx -s reload
done
