name: ci

# https://help.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#github-context
# https://help.github.com/en/actions/reference/events-that-trigger-workflows
on:
  #release:
  #  types: [published]
  push:
    branches: [ dev-maven ]

env:
  GITHUB_IMAGE_NAME: vscode
  DOCKER_IMAGE_NAME: suisrc/graalvm
  QUAY_REGISTRY: quay.io
  DOCKER_REGISTRY: docker.io
  GITHUB_REGISTRY: docker.pkg.github.com
  ALIYUN_REGISTRY: registry.cn-hongkong.aliyuncs.com

jobs:
  maven-jdk11-22.0.0.2:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: |
          REGISTRY_URL=$GITHUB_REGISTRY
          DOCKER_DIR=${{ github.job }}
          DOCKER_DIR=${DOCKER_DIR%*-}
          DOCKER_VER=${{ github.job }}
          DOCKER_VER=${DOCKER_VER#-*}
          DOCKER_BOS=${DOCKER_VER%-*}

          echo "${{ secrets.GITHUB_TOKEN }}" | docker login $REGISTRY_URL -u ${{ github.actor }} --password-stdin
          docker build ./$DOCKER_DIR --file ./$DOCKER_DIR/$DOCKER_BOS.Dockerfile --tag image
      - name: Push docker image
        run: |
          DOCKER_VER=${{ github.job }}
          VERSION=${DOCKER_VER#-*}
          REGISTRY_URL=$DOCKER_REGISTRY

          echo "${{ secrets.DOCKER_TOKEN }}" | docker login $REGISTRY_URL -u ${{ secrets.DOCKER_USER }} --password-stdin
          IMAGE_ID=$REGISTRY_URL/$DOCKER_IMAGE_NAME
          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION
          docker tag image $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION
      - name: Push quay image
        run: |
          DOCKER_VER=${{ github.job }}
          VERSION=${DOCKER_VER#-*}
          REGISTRY_URL=$QUAY_REGISTRY

          echo "${{ secrets.QUAY_TOKEN }}" | docker login $REGISTRY_URL -u ${{ secrets.QUAY_USER }} --password-stdin
          IMAGE_ID=$REGISTRY_URL/$DOCKER_IMAGE_NAME
          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION
          docker tag image $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION
