# github ci
name: Docker

on:
  #release:
  #  types: [published]
  push:
    branches: [ dev-php ]

env:
  GITHUB_IMAGE_NAME: vscode
  DOCKER_IMAGE_NAME: suisrc/vscode
  DOCKER_VERSION: '1.52.1'
  GITHUB_REGISTRY: docker.pkg.github.com
  QUAY_REGISTRY: quay.io
  DOCKER_REGISTRY: docker.io
  ALIYUN_REGISTRY: registry.cn-hongkong.aliyuncs.com

jobs:
  debian-php:
    #if: false
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: |
          REGISTRY_URL=$GITHUB_REGISTRY
          DOCKER_DIR=${{ github.job }}
          DOCKER_DIR=${DOCKER_DIR##*-}
          DOCKER_BOS=${{ github.job }}
          DOCKER_BOS=${DOCKER_BOS%%-*}

          echo "${{ secrets.GITHUB_TOKEN }}" | docker login $REGISTRY_URL -u ${{ github.actor }} --password-stdin
          docker build ./$DOCKER_DIR --file ./$DOCKER_DIR/$DOCKER_BOS.Dockerfile --tag image

      - name: Push docker image
        run: |
          REGISTRY_URL=$DOCKER_REGISTRY
          echo "${{ secrets.DOCKER_TOKEN }}" | docker login $REGISTRY_URL -u ${{ secrets.DOCKER_USER }} --password-stdin

          IMAGE_ID=$REGISTRY_URL/$DOCKER_IMAGE_NAME
          echo IMAGE_ID=$IMAGE_ID
          VERSION=$DOCKER_VERSION-${{ github.job }}
          echo VERSION=$VERSION

          docker tag image $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION
      
      - name: Push quay image
        run: |
          REGISTRY_URL=$QUAY_REGISTRY
          echo "${{ secrets.QUAY_TOKEN }}" | docker login $REGISTRY_URL -u ${{ secrets.QUAY_USER }} --password-stdin

          IMAGE_ID=$REGISTRY_URL/$DOCKER_IMAGE_NAME
          echo IMAGE_ID=$IMAGE_ID
          VERSION=$DOCKER_VERSION-${{ github.job }}
          echo VERSION=$VERSION

          docker tag image $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION

      - name: Push aliyun image
        run: |
          REGISTRY_URL=$ALIYUN_REGISTRY
          echo "${{ secrets.ALIYUN_TOKEN }}" | docker login $REGISTRY_URL -u ${{ secrets.ALIYUN_USER }} --password-stdin

          IMAGE_ID=$REGISTRY_URL/$DOCKER_IMAGE_NAME
          echo IMAGE_ID=$IMAGE_ID
          VERSION=$DOCKER_VERSION-${{ github.job }}
          echo VERSION=$VERSION

          docker tag image $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION
