name: ci

# https://help.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#github-context
# https://help.github.com/en/actions/reference/events-that-trigger-workflows
on:
  #release:
  #  types: [published]
  push:
    branches: [ vsas ]

# lite: vscode 轻量版本，cjk 字体不存在
# jammy: ubuntu 22.04基础镜像
# kclient: 修复了kasm 终端的一些问题和增加了一些功能
# nginx: jammy基础上安装了nginx
# sshd: nginx基础上安装了sshd
# vscode: vsccdr, vscpod; sshd基础上安装了vscode
#
# xface-~: 安装桌面环境 
# dev-~: 专注于开发环境
# ms-dev-~: 开发环境，使用 ms 插件库
# playwright-ms-dev-~: 开发环境，使用 playwright-ms 插件库

env:
  IMAGE_NAME: suisrc/webtop
  IMAGE_VERSION: 'dev-vsccdr-23122002'
  GITHUB_REGISTRY: ghcr.io
  DOCKER_REGISTRY: docker.io
  QUAY_REGISTRY: quay.io
  ALIYUN_REGISTRY: registry.cn-hongkong.aliyuncs.com

jobs:
  vsas:
    # if: false
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: |
          docker build -f "Dockerfile.${IMAGE_VERSION%%-*}" -t image --no-cache --build-arg BASE_IMAGE_TAG=${IMAGE_VERSION#*-} .

      - name: Push github image
        run: |
          REGISTRY_URL=$GITHUB_REGISTRY
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login $REGISTRY_URL -u ${{ github.actor }} --password-stdin

          IMAGE_ID=$REGISTRY_URL/$IMAGE_NAME
          echo IMAGE_ID=$IMAGE_ID
          VERSION=$IMAGE_VERSION  #-${{ github.job }}
          echo VERSION=$VERSION

          docker tag image $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION

      - name: Push docker image
        run: |
          REGISTRY_URL=$DOCKER_REGISTRY
          echo "${{ secrets.DOCKER_TOKEN }}" | docker login $REGISTRY_URL -u ${{ secrets.DOCKER_USER }} --password-stdin

          IMAGE_ID=$REGISTRY_URL/$IMAGE_NAME
          echo IMAGE_ID=$IMAGE_ID
          VERSION=$IMAGE_VERSION  #-${{ github.job }}
          echo VERSION=$VERSION

          docker tag image $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION
