# 用于修复异常的镜像
name: FixDocker

on:
  push:
    branches:
      - fix-master
env:
  DOCKER_VERSION: 1.44.2-11
  GITHUB_IMAGE_NAME: vscode
  DOCKER_IMAGE_NAME: suisrc/vscode

jobs:

  centos-graal:
    needs: centos
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: |
          REGISTRY_URL=docker.pkg.github.com
          DOCKER_DIR=${{ github.job }}
          DOCKER_DIR=${DOCKER_DIR##*-}
          DOCKER_BOS=${{ github.job }}
          DOCKER_BOS=${DOCKER_BOS%%-*}

          echo "${{ secrets.GITHUB_TOKEN }}" | docker login $REGISTRY_URL -u ${{ github.actor }} --password-stdin
          docker build ./$DOCKER_DIR --file ./$DOCKER_DIR/$DOCKER_BOS.Dockerfile --tag image

      - name: Push docker image
        run: |
          REGISTRY_URL=docker.io
          echo "${{ secrets.DOCKER_TOKEN }}" | docker login $REGISTRY_URL -u ${{ secrets.DOCKER_USER }} --password-stdin

          IMAGE_ID=$REGISTRY_URL/$DOCKER_IMAGE_NAME
          echo IMAGE_ID=$IMAGE_ID

          VERSION=DOCKER_VERSION-${{ github.job }}
          echo VERSION=$VERSION

          docker tag image $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION

      - name: Push aliyun image
        run: |
          REGISTRY_URL=registry.cn-beijing.aliyuncs.com
          echo "${{ secrets.ALIYUN_TOKEN }}" | docker login $REGISTRY_URL -u ${{ secrets.ALIYUN_USER }} --password-stdin

          IMAGE_ID=$REGISTRY_URL/$DOCKER_IMAGE_NAME
          echo IMAGE_ID=$IMAGE_ID

          VERSION=DOCKER_VERSION-${{ github.job }}
          echo VERSION=$VERSION

          docker tag image $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION

      - name: Push quay image
        run: |
          REGISTRY_URL=quay.io
          echo "${{ secrets.QUAY_TOKEN }}" | docker login $REGISTRY_URL -u ${{ secrets.QUAY_USER }} --password-stdin

          IMAGE_ID=$REGISTRY_URL/$DOCKER_IMAGE_NAME
          echo IMAGE_ID=$IMAGE_ID

          VERSION=DOCKER_VERSION-${{ github.job }}
          echo VERSION=$VERSION

          docker tag image $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION

  debian-graal:
    needs: debian
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: |
          REGISTRY_URL=docker.pkg.github.com
          DOCKER_DIR=${{ github.job }}
          DOCKER_DIR=${DOCKER_DIR##*-}
          DOCKER_BOS=${{ github.job }}
          DOCKER_BOS=${DOCKER_BOS%%-*}

          echo "${{ secrets.GITHUB_TOKEN }}" | docker login $REGISTRY_URL -u ${{ github.actor }} --password-stdin
          docker build ./$DOCKER_DIR --file ./$DOCKER_DIR/$DOCKER_BOS.Dockerfile --tag image

      - name: Push docker image
        run: |
          REGISTRY_URL=docker.io
          echo "${{ secrets.DOCKER_TOKEN }}" | docker login $REGISTRY_URL -u ${{ secrets.DOCKER_USER }} --password-stdin

          IMAGE_ID=$REGISTRY_URL/$DOCKER_IMAGE_NAME
          echo IMAGE_ID=$IMAGE_ID

          VERSION=DOCKER_VERSION-${{ github.job }}
          echo VERSION=$VERSION

          docker tag image $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION

  centos-golang:
    needs: centos
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: |
          REGISTRY_URL=docker.pkg.github.com
          DOCKER_DIR=${{ github.job }}
          DOCKER_DIR=${DOCKER_DIR##*-}
          DOCKER_BOS=${{ github.job }}
          DOCKER_BOS=${DOCKER_BOS%%-*}

          echo "${{ secrets.GITHUB_TOKEN }}" | docker login $REGISTRY_URL -u ${{ github.actor }} --password-stdin
          docker build ./$DOCKER_DIR --file ./$DOCKER_DIR/$DOCKER_BOS.Dockerfile --tag image

      - name: Push docker image
        run: |
          REGISTRY_URL=docker.io
          echo "${{ secrets.DOCKER_TOKEN }}" | docker login $REGISTRY_URL -u ${{ secrets.DOCKER_USER }} --password-stdin

          IMAGE_ID=$REGISTRY_URL/$DOCKER_IMAGE_NAME
          echo IMAGE_ID=$IMAGE_ID

          VERSION=DOCKER_VERSION-${{ github.job }}
          echo VERSION=$VERSION

          docker tag image $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION

      - name: Push aliyun image
        run: |
          REGISTRY_URL=registry.cn-beijing.aliyuncs.com
          echo "${{ secrets.ALIYUN_TOKEN }}" | docker login $REGISTRY_URL -u ${{ secrets.ALIYUN_USER }} --password-stdin

          IMAGE_ID=$REGISTRY_URL/$DOCKER_IMAGE_NAME
          echo IMAGE_ID=$IMAGE_ID

          VERSION=DOCKER_VERSION-${{ github.job }}
          echo VERSION=$VERSION

          docker tag image $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION

      - name: Push quay image
        run: |
          REGISTRY_URL=quay.io
          echo "${{ secrets.QUAY_TOKEN }}" | docker login $REGISTRY_URL -u ${{ secrets.QUAY_USER }} --password-stdin

          IMAGE_ID=$REGISTRY_URL/$DOCKER_IMAGE_NAME
          echo IMAGE_ID=$IMAGE_ID

          VERSION=DOCKER_VERSION-${{ github.job }}
          echo VERSION=$VERSION

          docker tag image $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION

  centos-graal-jdk11:
    needs: centos
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: |
          REGISTRY_URL=docker.pkg.github.com
          DOCKER_DIR=graal
          DOCKER_BOS=centos-jdk11

          echo "${{ secrets.GITHUB_TOKEN }}" | docker login $REGISTRY_URL -u ${{ github.actor }} --password-stdin
          docker build ./$DOCKER_DIR --file ./$DOCKER_DIR/$DOCKER_BOS.Dockerfile --tag image

      - name: Push docker image
        run: |
          REGISTRY_URL=docker.io
          echo "${{ secrets.DOCKER_TOKEN }}" | docker login $REGISTRY_URL -u ${{ secrets.DOCKER_USER }} --password-stdin

          IMAGE_ID=$REGISTRY_URL/$DOCKER_IMAGE_NAME
          echo IMAGE_ID=$IMAGE_ID

          VERSION=DOCKER_VERSION-${{ github.job }}
          echo VERSION=$VERSION

          docker tag image $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION

      - name: Push aliyun image
        run: |
          REGISTRY_URL=registry.cn-beijing.aliyuncs.com
          echo "${{ secrets.ALIYUN_TOKEN }}" | docker login $REGISTRY_URL -u ${{ secrets.ALIYUN_USER }} --password-stdin

          IMAGE_ID=$REGISTRY_URL/$DOCKER_IMAGE_NAME
          echo IMAGE_ID=$IMAGE_ID

          VERSION=DOCKER_VERSION-${{ github.job }}
          echo VERSION=$VERSION

          docker tag image $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION

      - name: Push quay image
        run: |
          REGISTRY_URL=quay.io
          echo "${{ secrets.QUAY_TOKEN }}" | docker login $REGISTRY_URL -u ${{ secrets.QUAY_USER }} --password-stdin

          IMAGE_ID=$REGISTRY_URL/$DOCKER_IMAGE_NAME
          echo IMAGE_ID=$IMAGE_ID

          VERSION=DOCKER_VERSION-${{ github.job }}
          echo VERSION=$VERSION

          docker tag image $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION