# 用于修复异常的镜像
name: DockerFix

on:
  push:
    branches: [ fix-master ]

env:
  GITHUB_IMAGE_NAME: vscode
  DOCKER_IMAGE_NAME: suisrc/vscode
  DOCKER_VERSION: 1.45.1-01
  GITHUB_REGISTRY: docker.pkg.github.com
  QUAY_REGISTRY: quay.io
  DOCKER_REGISTRY: docker.io
  ALIYUN_REGISTRY: registry.cn-hongkong.aliyuncs.com

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: test
        run: echo "Hello World"
############################################################################################
