# 用于修复异常的镜像
name: Fixdocker

on:
  push:
    branches:
      - fix-master
env:
  DOCKER_VERSION: 1.44.2-13
  GITHUB_IMAGE_NAME: vscode
  DOCKER_IMAGE_NAME: suisrc/vscode

#          VERSION=DOCKER_VERSION-${{ github.job }}
#          echo VERSION=$VERSION
jobs:
###########################################################################################

  centos:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: |
          docker build ./vscode --file ./vscode/centos.Dockerfile --tag image

      - name: Push github image
        run: |
          REGISTRY_URL=docker.pkg.github.com
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login $REGISTRY_URL -u ${{ github.actor }} --password-stdin

          IMAGE_ID=$REGISTRY_URL/${{ github.repository }}/$GITHUB_IMAGE_NAME
          #IMAGE_ID=$REGISTRY_URL/$DOCKER_IMAGE_NAME

          # Change all uppercase to lowercase
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          echo IMAGE_ID=$IMAGE_ID

          VERSION=DOCKER_VERSION-${{ github.job }}
          echo VERSION=$VERSION

          docker tag image $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION
